### ISSUE TITLE
Update NuGet package to latest sources

### ISSUE THREAD

**Issue by ndastur** [BuddyPlatform/Buddy-DotNET-SDK#100]
I came to use the Get My Identities method. A couple of things:

1) the documentation is incorrect as a User model is not returned.

2) I went to create a pull request and found that the source from a year ago does have an identities model leaving me to come to the conclusion that the NuGet package is over a year old?

**Comment by bradserbuddy** [comment]
Thanks for your feedback. We have a newer version renamed as "Buddy-WindowsIoTCore-SDK', check it out here: http://www.nuget.org/packages/Buddy-WindowsIoTCore-SDK/0.1.1-beta

Thanks,
Brad

**Comment by ndastur** [comment]
Thanks Brad, but this doesn't work as the new package depends upon M2Mqtt which fails to install on Xamarin.iOS and .Android :(
