### ISSUE TITLE
Latest Buddy for .Net NuGet won't install

### ISSUE THREAD

**Issue by ndastur** [BuddyPlatform/Buddy-DotNET-SDK#101]
Hi,

Unfortunitly the new SDK for .net depends upon M2Mqtt which fails to install on Xamarin.iOS and .Android. 

Maybe something like this would help
https://github.com/mFourLabs/KittyHawkMQ
https://www.nuget.org/packages/System.Net.Mqtt/0.3.6-pre
https://www.nuget.org/packages/System.Net.Mqtt/

but I think this looks like the most promising. Just not a NuGet yet
https://github.com/markallanson/nmqtt

**Comment by bradserbuddy** [comment]
I'll look into this, thanks for the report.

**Comment by ndastur** [comment]
Hi @bradserbuddy any news on this yet??

**Comment by bradserbuddy** [comment]
For Xamarin, I recommend using the older .NET SDK from here: https://www.nuget.org/packages/BuddyPlatformSdk/. If you run into any issues let me know.
