### ISSUE TITLE
BuddyClient.GetAccessToken() returns null on multiple async calls

### ISSUE THREAD

**Issue by xyziemba** [BuddyPlatform/Buddy-DotNET-SDK#87]
[GetAccessToken] (https://github.com/BuddyPlatform/Buddy-DotNET-SDK/blob/develop/Src/BuddyClient.cs#L297) doesn't block and yield additional calls to itself when awaiting GetDeviceToken(). Instead, subsequent calls will return null until `await GetDeviceToken()` returns for the first request.

This breaks somewhat idiomatic expressions such as this:
```
BuddySDK.Buddy.Init("id","key");
var tasksToWaitFor = listOfStuffToInject.ForEach(
   (e) =>
      BuddySDK.Buddy.PostAsync<BuddySDK.Models.ModelType>("/endpoint", e);
)};
Task.WaitAll(tasksToWaitFor);
// or
await Task.WhenAll(tasksToWaitFor); // continue from here
```

**Comment by bradserbuddy** [comment]
Makes sense. I'll work up a solution

**Comment by xyziemba** [comment]
FWIW, I saw the AsyncLock class after filing this, and I'm guessing fixing this should mostly just require wrapping that method in AsyncLock.

**Comment by bradserbuddy** [comment]
Yes I was thinking the same thing!

**Comment by bradserbuddy** [comment]
Xy, here's a commit that targets this issue. Can you take a look? https://github.com/bradserbuddy/Buddy-DotNET-SDK/commit/3f9278f38870f3424431f65fb13bf046abf6e666

**Comment by xyziemba** [comment]
Looks mostly good. My only concern was with removing `_processingAuthFailure` and the interlocked increment/decrements associated with it. I might be misunderstanding something, though, so feel free to grab me tomorrow.
